### ISSUE TITLE
Assginment 8 : TODO LIST(4)

### ISSUE THREAD

**Issue by Jimoou** [Jimoou/wanted-pre-onboarding-frontend#10]
* [x] TODO 우측에 수정버튼과 삭제 버튼을 만듬.
   * [x]  수정 버튼에는 `data-testid="modify-button"속성 부여
   * [x]  삭제 버튼에는 `data-testid="delete-button"속성 부여
