### ISSUE TITLE
Assignment 5 : TODO LIST(1)

### ISSUE THREAD

**Issue by Jimoou** [Jimoou/wanted-pre-onboarding-frontend#7]
* [x] `/todo`경로에 접속하면 투두 리스트의 목록을 볼 수 있도록 구현
* [x] 목록에서는 TODO의 내용과 완료 여부가 표시
* [x] TODO의 완료 여부는 `<input type="checkbox" />`를 통해 표현
* [x] TODO는 `<li>` tag를 이용
